### ISSUE TITLE
Database connection timeouts not configured correctly

### ISSUE THREAD

**Issue by jbcpollak** [spring-cloud/spring-cloud-cloudfoundry#4]
We are using Spring-Cloud connector with Spring-Boot on an application deployed to Pivotal Web Services. Spring-Cloud-Cloudfoundry configures us to talk to our cleardb database automatically.

We are also using the Hikari Connection pool.

We get frequent warnings in our log files from Hikari that our connections have timed out. This appears to be because our server is used infrequently, so clearDb closes our connections on their side, then the connection pool discovers this and a huge stack trace is logged.

I found other people having similar issues online. Although they may not be with Spring, or even PWS, I would suggest this indicates a general problem which could be solved more gracefully by having the connector provide more information, or at least reasonable defaults.

Here is how we are configuring our connection:

```
@Configuration
@Profile("mysql-cloud")
public class MysqlCloudConfiguration extends AbstractCloudConfig {

    @Bean
    public DataSource dataSource() {
        return connectionFactory().dataSource();
    }
}
```

I have tried to set our connection parameters directly, but they don't seem to take effect. I think that is a Spring-Boot issue.

Here are the connection parameters we end up using from Hikari. These are the defaults, and I think that the connector should be setting `connectionTimeout` and `idleTimeout`.

```
DEBUG com.zaxxer.hikari.HikariConfig - connectionInitSql............... 
DEBUG com.zaxxer.hikari.HikariConfig - connectionTestQuery............./* ping */ SELECT 1 
DEBUG com.zaxxer.hikari.HikariConfig - connectionTimeout...............30000 
DEBUG com.zaxxer.hikari.HikariConfig - dataSource...................... 
DEBUG com.zaxxer.hikari.HikariConfig - dataSourceClassName............. 
DEBUG com.zaxxer.hikari.HikariConfig - dataSourceJNDI.................. 
DEBUG com.zaxxer.hikari.HikariConfig - dataSourceProperties............{password=<masked>} 
DEBUG com.zaxxer.hikari.HikariConfig - driverClassName................. 
DEBUG com.zaxxer.hikari.HikariConfig - idleTimeout.....................600000 
DEBUG com.zaxxer.hikari.HikariConfig - initializationFailFast..........false 
DEBUG com.zaxxer.hikari.HikariConfig - isolateInternalQueries..........false 
DEBUG com.zaxxer.hikari.HikariConfig - jdbc4ConnectionTest.............false 
DEBUG com.zaxxer.hikari.HikariConfig - jdbcUrl.........................jdbc:mysql://us-cdbr-iron-east-01.cleardb.net:3306/<redacted>&reconnect=true 
DEBUG com.zaxxer.hikari.HikariConfig - leakDetectionThreshold..........0 
DEBUG com.zaxxer.hikari.HikariConfig - maxLifetime.....................1800000 
DEBUG com.zaxxer.hikari.HikariConfig - maximumPoolSize.................4 
DEBUG com.zaxxer.hikari.HikariConfig - metricsTrackerClassName.........com.zaxxer.hikari.metrics.CodaHaleMetricsTracker 
DEBUG com.zaxxer.hikari.HikariConfig - minimumIdle.....................4 
```

Here are some similar online issues:

http://support.run.pivotal.io/entries/24868832-Network-problems-with-MySQL
http://stackoverflow.com/questions/24046843/connection-closed-error-in-heroku-cleardb-addon
https://getsatisfaction.com/cleardb/topics/connection_error_mysql2_error_mysql_server_has_gone_away

Here is the exception we are getting:

```
Here is the exception:

20:52:30.178 01:52:29.980 [http-nio-61032-exec-6] WARN com.zaxxer.hikari.pool.HikariPool - Exception during keep alive check, that means the connection (com.mysql.jdbc.JDBC4Connection@62fc8df6) must be dead.

com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 349,959 milliseconds ago. The last packet sent successfully to the server was 1 milliseconds ago.

at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_31-]

at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_31-]

at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_31-]

at java.lang.reflect.Constructor.newInstance(Constructor.java:408) ~[na:1.8.0_31-]

at com.mysql.jdbc.Util.handleNewInstance(Util.java:377) ~[mysql-connector-java-5.1.34.jar!/:5.1.34]

at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1036) ~[mysql-connector-java-5.1.34.jar!/:5.1.34]

at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3427) ~[mysql-connector-java-5.1.34.jar!/:5.1.34]

at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3327) ~[mysql-connector-java-5.1.34.jar!/:5.1.34]

at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3814) ~[mysql-connector-java-5.1.34.jar!/:5.1.34]

at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435) ~[mysql-connector-java-5.1.34.jar!/:5.1.34]

at com.mysql.jdbc.ConnectionImpl.pingInternal(ConnectionImpl.java:3971) ~[mysql-connector-java-5.1.34.jar!/:5.1.34]

at com.mysql.jdbc.ConnectionImpl.ping(ConnectionImpl.java:3951) ~[mysql-connector-java-5.1.34.jar!/:5.1.34]

at com.mysql.jdbc.StatementImpl.doPingInstead(StatementImpl.java:1509) ~[mysql-connector-java-5.1.34.jar!/:5.1.34]

at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1395) ~[mysql-connector-java-5.1.34.jar!/:5.1.34]

at com.zaxxer.hikari.pool.HikariPool.isConnectionAlive(HikariPool.java:460) [HikariCP-2.1.0.jar!/:na]

at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:175) [HikariCP-2.1.0.jar!/:na]

at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:111) [HikariCP-2.1.0.jar!/:na]

at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:139) [hibernate-core-4.3.7.Final.jar!/:4.3.7.Final]

at org.hibernate.internal.AbstractSessionImpl$NonContextualJdbcConnectionAccess.obtainConnection(AbstractSessionImpl.java:380) [hibernate-core-4.3.7.Final.jar!/:4.3.7.Final]

at org.hibernate.engine.jdbc.internal.LogicalConnectionImpl.obtainConnection(LogicalConnectionImpl.java:228) [hibernate-core-4.3.7.Final.jar!/:4.3.7.Final]

at org.hibernate.engine.jdbc.internal.LogicalConnectionImpl.getConnection(LogicalConnectionImpl.java:171) [hibernate-core-4.3.7.Final.jar!/:4.3.7.Final]

at org.hibernate.internal.SessionImpl.connection(SessionImpl.java:450) [hibernate-core-4.3.7.Final.jar!/:4.3.7.Final]

at sun.reflect.GeneratedMethodAccessor120.invoke(Unknown Source) ~[na:na]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_31-]

at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_31-]

at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:202) [spring-core-4.1.4.RELEASE.jar!/:4.1.4.RELEASE]

at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:187) [spring-core-4.1.4.RELEASE.jar!/:4.1.4.RELEASE]

at org.springframework.orm.jpa.vendor.HibernateJpaDialect$HibernateConnectionHandle.doGetConnection(HibernateJpaDialect.java:378) [spring-orm-4.1.4.RELEASE.jar!/:4.1.4.RELEASE]

at org.springframework.orm.jpa.vendor.HibernateJpaDialect.beginTransaction(HibernateJpaDialect.java:146) [spring-orm-4.1.4.RELEASE.jar!/:4.1.4.RELEASE]

at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:380) [spring-orm-4.1.4.RELEASE.jar!/:4.1.4.RELEASE]

at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373) [spring-tx-4.1.4.RELEASE.jar!/:4.1.4.RELEASE]

at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:457) [spring-tx-4.1.4.RELEASE.jar!/:4.1.4.RELEASE]

at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:276) [spring-tx-4.1.4.RELEASE.jar!/:4.1.4.RELEASE]

at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) [spring-tx-4.1.4.RELEASE.jar!/:4.1.4.RELEASE]

at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [spring-aop-4.1.4.RELEASE.jar!/:4.1.4.RELEASE]

at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136) [spring-tx-4.1.4.RELEASE.jar!/:4.1.4.RELEASE]

at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [spring-aop-4.1.4.RELEASE.jar!/:4.1.4.RELEASE]
```

**Comment by scottfrederick** [comment]
@jbcpollak I think this issue belongs over in the [Spring Cloud Connectors](https://github.com/spring-cloud/spring-cloud-connectors) project, but we can have a discussion here and create any necessary issues there. 

I assume you are using your fork of SCC that has your (unmerged) Hikari PR included? 

I don't think SCC should be guessing at defaults for config parameters, but should just use the libraries' built-in defaults and rely on apps to customize that as needed. Connection parameters like the ones you are describing should be set using the [form of `connectionFactory().dataSource()` that takes a `ServiceConnectorConfig` argument](https://github.com/spring-cloud/spring-cloud-connectors/blob/master/spring-cloud-spring-service-connector/src/main/java/org/springframework/cloud/config/java/AbstractCloudConfig.java#L129-129).

 [`DataSourceConfig`](https://github.com/spring-cloud/spring-cloud-connectors/blob/master/spring-cloud-spring-service-connector/src/main/java/org/springframework/cloud/service/relational/DataSourceConfig.java#L10-10), with its `ConnectionConfig` parameter, supports setting arbitrary bean values on the connection object if that works. Additional parameters could be added to `DataSourceConfig` or `PooledServiceConnectorConfig` also if necessary.

**Comment by jbcpollak** [comment]
@scottfrederick - Wow, I had totally forgotten about the PR until I started digging through the code to make sure my answer was sensible.  I suspect you may be right that SCC is a better forum, I had totally forgotten which library the customized code was in (or even that I had any) until now.

> I don't think SCC should be guessing at defaults for config parameters, but should just use the libraries' built-in defaults and rely on apps to customize that as needed. Connection parameters like the ones you are describing should be set using the form of connectionFactory().dataSource() that takes a ServiceConnectorConfig argument.

But it does exactly that:

```
		    // choose sensible values so that we set max connection pool size to what
		    // free tier services on Cloud Foundry and Heroku allow
		    serviceConnectorConfig = new DataSourceConfig(new PoolConfig(4, 30000), null);
```

is from:

https://github.com/spring-cloud/spring-cloud-connectors/blob/master/spring-cloud-spring-service-connector/src/main/java/org/springframework/cloud/service/relational/DbcpLikePooledDataSourceCreator.java

(I based my Hikari code in the pull request off this code, so it has the same comment)

I agree SCC should not be guessing at parameters, but rather than using the libraries built-in defaults, I would argue that if the PaaS has specific restrictions (like Cloud Foundry and Heroku impose on maximum number of connections or timeout limits), the PaaS should be providing those settings and SCC should be passing them to the application.

Since SCC seems to already be making (handy) assumptions about the maximum number of connections, shouldn't it also help configure the timeouts correctly?

If the point of SCC and Spring Boot is to provide an "it just works" platform for writing code, shouldn't all important parameters be provided / suggested by that platform?

Thanks for the tips on providing customization. Is there a way to adapt the Spring-Boot DataSource configuration (see `DataSourceConfigMetadata` in that project) to a `DataSourceConfig` in SCC so that we don't have to have duplicate configuration in our properties files?

**Comment by jbcpollak** [comment]
BTW: that comment from `DbcpLikePooledDataSourceCreator` specifically mentions Cloud Foundry and Heroku in a more generic project... That implies to me maybe this project should be providing those settings to the main project, ideally by reading them from the PaaS itself.

**Comment by dsyer** [comment]
Please move this discussion to SCC.
